package com.gcsoft.autots.script.test;

// Generated by Selenium IDE
import java.awt.Robot;
import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Test {
	@SuppressWarnings("unused")
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public void doTest(WebDriver driver, Robot robot, String url, String browserType) {

		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		driver.get(url);
//		driver.manage().window().setSize(new Dimension(1059, 846));
		@SuppressWarnings("unused")
		WebDriverWait wait = new WebDriverWait(driver, 30);
		driver.findElement(By.id("UserName")).click();
		driver.findElement(By.id("UserName")).sendKeys("pd-admin");
		driver.findElement(By.id("Password")).sendKeys("ebt123450");
		driver.findElement(By.id("LoginBtn")).click();
//		driver.switchTo().frame(1);
//		driver.switchTo().frame(1);
//		driver.switchTo().frame(0);
//		driver.switchTo().frame(1);
//		driver.findElement(By.linkText("111")).click();
//		driver.findElement(By.linkText("111")).sendKeys(Keys.ENTER);
//		wait.until(ExpectedConditions.visibilityOfElementLocated((By.linkText("333"))));
//		driver.findElement(By.linkText("333")).click();
//		driver.findElement(By.linkText("333")).sendKeys(Keys.ENTER);
//
//		driver.switchTo().defaultContent();
//		driver.switchTo().frame("F_AppArea"); // 0:F_AppLancherÅA 1:F_AppArea
//		driver.switchTo().frame("Iframe1"); // 0:F_DocMngBarÅA 1:Iframe1
//		driver.switchTo().frame("F_DocList"); // 0:F_FoldTree
//		driver.switchTo().frame("F_DocLstTbl");// 0:F_TreeBarÅA 1:F_TreeField
//
//		driver.findElement(By.id("RptEffectListTable_ctl04_ImgBtnChkOut1")).click();
//		driver.findElement(By.id("RptEffectListTable_ctl04_ImgBtnChkOut1")).sendKeys(Keys.ENTER);
//		driver.switchTo().frame(1);
//		driver.findElement(By.id("BtnCancel")).click();
//		driver.findElement(By.id("BtnCancel")).sendKeys(Keys.ENTER);
//		driver.switchTo().defaultContent();
	}
}
