package com.gcsoft.autots.script.test;

// OLD I test wstest
// Generated by Selenium IDE
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.gcsoft.autots.utils.CommonUtil;
import com.gcsoft.autots.utils.ScreenshotUtil;

@SuppressWarnings("unused")
public class wstest {
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@SuppressWarnings("unchecked")
	public String waitForWindow(WebDriver driver, int timeout) {
		try {
			Thread.sleep(timeout);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		Set<String> whNow = driver.getWindowHandles();
		Set<String> whThen = (Set<String>) vars.get("window_handles"); 
		if (whNow.size() > whThen.size()) {
			whNow.removeAll(whThen);
		}
		return whNow.iterator().next();
	}

	@SuppressWarnings("static-access")
	public void doTest(WebDriver driver, Robot robot, String url, String browserType) throws Exception {
		ScreenshotUtil screen = new ScreenshotUtil();

		Actions action = new Actions(driver);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		driver.get(url);
		driver.findElement(By.id("UserName")).click();
		driver.findElement(By.id("UserName")).sendKeys("pd-admin");
		driver.findElement(By.id("Password")).click();
		driver.findElement(By.id("Password")).sendKeys("pd-admin");

		screen.getScreenshot(driver, "D:\\Image\\IE_1_登录页面.PNG", null);

		driver.findElement(By.id("LoginBtn")).click();
		driver.switchTo().frame("F_AppArea");
		driver.switchTo().frame("F_DocMngBar");
	    driver.findElement(By.id("BtnDocRegist")).sendKeys(Keys.ENTER);
	    driver.switchTo().defaultContent();
	    driver.switchTo().frame("F_AppArea");
	    driver.switchTo().frame("F_DocMngMain");
	    driver.switchTo().frame("F_DocRegistMain");
	    driver.switchTo().frame("F_DocRegistLeft");	    
	    
		screen.getScreenshot(driver, "D:\\Image\\IE_2_登录.PNG", null);
		
		robot.mouseMove(270, 780);
		robot.mousePress(KeyEvent.BUTTON1_MASK);
		robot.mouseRelease(KeyEvent.BUTTON1_MASK);
//	    driver.findElement(By.id("CheckBoxNoLimit")).click();
	    driver.findElement(By.id("TxtMonth")).click();
	    driver.findElement(By.id("TxtMonth")).sendKeys("啊啊�");    		
		driver.findElement(By.id("TxtMonth")).sendKeys("9");
		
		screen.getScreenshot(driver, "D:\\Image\\IE_3_验证.PNG", null);
	}
}
